server {
  listen 80;
  server_name localhost;
  root /usr/share/nginx/html;
  index index.html;

  location / {
    try_files $uri $uri/ /index.html;
  }

  location /patients {
    proxy_pass http://api-gateway:80;
    proxy_http_version 1.1;
    proxy_set_header Host $host;
  }

  location /appointments {
    proxy_pass http://api-gateway:80;
    proxy_http_version 1.1;
    proxy_set_header Host $host;
  }

  location /records {
    proxy_pass http://api-gateway:80;
    proxy_http_version 1.1;
    proxy_set_header Host $host;
  }

  location /notifications {
    proxy_pass http://api-gateway:80;
    proxy_http_version 1.1;
    proxy_set_header Host $host;
  }

  location = /api/health {
    proxy_pass http://api-gateway:80/health;
    proxy_http_version 1.1;
  }
}
